select * from customer limit 20;

#Q1 what is the total revenue generated by male and female customers
select gender, sum(`purchase_amount_(usd)`) as revenue
from customer
group by gender

#Q2 which customers used a discount but still spent more than the average purchase amount
select customer_id, discount_applied,purchase_amount
from customer
where discount_applied = 'yes'
and purchase_amount>=(select avg (purchase_amount)from customer);


ALTER TABLE customer
RENAME COLUMN `purchase_amount_(usd)` TO purchase_amount;

#Q3 which are the top5 products with the highest average review rating
select item_purchased, round(avg (review_rating),2) as 'average revenue'
from customer
group by item_purchased
order by avg (review_rating) desc
limit 5;

#Q4 compare the average purchase amount between standard and express shipping
select shipping_type,
round(avg(purchase_amount),2) as average
from customer
where shipping_type in ('standard', 'express')
group by shipping_type


#Q5 do subscribed customers spend more? compare average spend and total revenue between subscribers and non_subscribers
select subscription_status ,
count(customer_id) as total_customers,
round(avg(purchase_amount),2) as avg_spend,
round(sum(purchase_amount),2) as total_revenue
from customer
group by subscription_status
order by total_revenue, avg_spend desc;

#Q6 which 5 products have the highest percenatge of purchases with discount_applied
select item_purchased,
round(sum(case when discount_applied ='yes'then 1 else 0 end) /COUNT(*)*100,2)as discount_rate
from customer
group by item_purchased
order by discount_rate desc 
limit 5;

#segment customers into new, returning, and loyal based on their total number of previous purchase 
#and show the count of each segment

with customer_type as (
select customer_id, previous_purchases,
case
when previous_purchases= 1 then 'new'
when previous_purchases between 2 and 10 then 'returning'
else 'loyal'
end as customer_segment from customer
)
select customer_segment, count(*) as 'number of customers'
from customer_type
group by customer_segment

#8what are the top 3 most purchased prodducts within category

select item_rank, category, item_purchased, total_orders
from item_counts
where item_rank <=3;            #ignore the code


WITH item_counts AS (
    SELECT category,
           item_purchased,
           COUNT(customer_id) AS total_orders,
           ROW_NUMBER() OVER (
               PARTITION BY category
               ORDER BY COUNT(customer_id) DESC
           ) AS item_rank
    FROM customer
    GROUP BY category, item_purchased
)
SELECT item_rank,
       category,
       item_purchased,
       total_orders
FROM item_counts
WHERE item_rank <= 3;


#are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe?
select subscription_status,
count(customer_id) as repeat_buyers
from customer
where previous_purchases > 5
group by subscription_status

#Q10 what is the revenue contribution of each age group
select age,
sum(purchase_amount) as total_revenue
from customer
group by age
order by total_revenue desc;
















